### ISSUE TITLE
After use TSCppDefineClassFunc I need to use twice :q to quit neovim.

### ISSUE THREAD

**Issue by chriztheanvill** [Badhi/nvim-treesitter-cpp-tools#18]
Hi. I love your plugin, and trying to add to my keymaps, I realize that TSCppDefineClassFunc has a little bug.
* After use TSCppDefineClassFunc I need to use twice :q to quit neovim.

Also I would like to use like this:
map("n", "<leader>rd" ":TSCppDefineClassFunc <cr> :tabedit %:p:h/${UseInput}.cpp", noremap = true)

But doesn't work. I think the preview part, doesn't let me use :tabedit ~~~.

Note: ${UseInput} was a example, right now I dont know how to implement this.

**Comment by Badhi** [comment]
Hi Thanks for trying out the plugin. I believe these are two separate issue isnt it? 

1. Could you explain a bit more about the steps you followed which caused you to enter :q twice to exit neovim? Dont think i can recreate the issue
2. Like  you said since `TSCppDefineClassFunc ` is interactive, I'm not sure if we can combine the `TSCppDefineClassFunc` with other operations

**Comment by chriztheanvill** [comment]
1) I think the problem comes with which-key, I set it: ``` :TSCppDefineClassFunc <cr> ````  in normal mode, and has this issue.
2) Yes, it works, but with a little issue:
``` d = {":TSCppDefineClassFunc<cr> :tabedit %:p:h/file.cpp", "Define other File", noremap = true}, ```
Shows this message:
   nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text

**Comment by Badhi** [comment]
1. Sorry what is "which-key" ?
2. Okay seems like I need to use the new API. Is it just a warning? if its a warning I hope you can continue with it for now

**Comment by chriztheanvill** [comment]
1) https://github.com/folke/which-key.nvim
2) Yes, its just a warning.
