### ISSUE TITLE
thanks for your good plugin, please add a new feature

### ISSUE THREAD

**Issue by paopaol** [Badhi/nvim-treesitter-cpp-tools#19]
Now it's an implementation that selects the entire class to generate the source files. Is it possible to add a new function signature or method signature that selects the specified and then add the specified method to the source file. It's like qtcreator's add definition in xxx.cpp.

**Comment by Badhi** [comment]
thanks for the request. I have a WIP branch -  [op_handlers](https://github.com/Badhi/nvim-treesitter-cpp-tools/tree/refactor/op_handlers) that lets you define your own action for the output result (class function implementation out when a definition is selected)

```lua
custom_impl_commands = {                                                             
    TSCustomImp = {                                                               
        output_cb = function (output_str, context) print(output_str) end
    }  
}                                                                                    
```

If you give the above config to the existing `nt_cpp_tools` config table, then you can do the same thing that you do for `TSCppDefineClassFunc` except the final output result will be passed to the `output_cb` function. So in this case it should just print the output string.

I also have created a boilerplate implementation to just add the text to the respective `xx.cpp` file as you've mentioned. For that you can give ` require'nvim-treesitter.nt-cpp-tools.output_handlers'.add_to_cpp ` to `output_cb`

Like this,
```lua
custom_impl_commands = {                                                             
    TSCustomImp = {                                                               
        output_cb = require'nvim-treesitter.nt-cpp-tools.output_handlers'.add_to_cpp 
    }  
}                                                                                    
```

Could you please try it out and let me know if it serves your purpose. Since `add_to_cpp`is a very basic implementation you can add a more refined version yourself as well

**Comment by paopaol** [comment]
thanks very mush, i will try it!

**Comment by Badhi** [comment]
```lua
 custom_define_class_function_commands = { -- optional
        TSCppImplWrite = {
            output_handle = require'nvim-treesitter.nt-cpp-tools.output_handlers'.get_add_to_cpp()
        }
        --[[
        <your impl function custom command name> = {
            output_handle = function (str, context) 
                -- string contains the class implementation
                -- do whatever you want to do with it
            end
        }
        ]]
    }
```

Merged the changes with some more minor changes mentioned above in the config.

**Comment by Badhi** [comment]
enhancement added with #22
